version: '3.8'

services:
  shop-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: shop-api
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - ../.env
    ports:
      - "8080:8080"
#      - "2345:2345"
#    command: "dlv debug ./cmd/server --headless --listen=:2345 --api-version=2 --accept-multiclient"
    command: ["/build/ShopItemsTgBot"] #["go", "run", "cmd/server/main.go"]
    depends_on:
      - postgres
      - redis
    networks:
      - shop_api_net
  postgres:
    image: postgres:13
    container_name: shop-db
    env_file:
      - ../.env
    volumes:
      - ../scripts/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - shop_api_net
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shop_api_net

networks:
  shop_api_net:
    driver: bridge

volumes:
  db_data: